export default function Terms() {
  const Section = ({ title, children }) => (
    <div className="card" style={{ marginBottom: 16 }}>
      <h2 style={{ fontSize: 16, fontWeight: 700, marginBottom: 10 }}>{title}</h2>
      <div style={{ color: 'var(--gray-700)', lineHeight: 1.8, fontSize: 14 }}>{children}</div>
    </div>
  );

  return (
    <div className="page">
      <div className="container" style={{ maxWidth: 700 }}>
        <h1 style={{ fontSize: 26, fontWeight: 800, marginBottom: 8 }}>Terms of Service</h1>
        <p style={{ color: 'var(--gray-500)', marginBottom: 24 }}>Last updated {new Date().toLocaleDateString()}</p>

        <Section title="1. What this is">
          <p>TutorPulseAI is a personal study tool that uses AI to turn uploaded homework and photos
          into summaries, flashcards, and quizzes. It's built and maintained by a student, not a
          commercial company.</p>
        </Section>

        <Section title="2. Using the service">
          <p>You must provide accurate information when creating an account and are responsible for
          keeping your password secure. You agree not to upload illegal, copyrighted material you
          don't have rights to, or content that violates your school's academic integrity policies.</p>
        </Section>

        <Section title="3. AI-generated content">
          <p>Summaries, flashcards, and quizzes are generated by AI and may contain mistakes,
          omissions, or inaccuracies. Always verify important information against your original
          material or a teacher before relying on it for graded work.</p>
        </Section>

        <Section title="4. Your content">
          <p>You retain ownership of anything you upload. Sharing a study pack via a public link makes
          its content viewable by anyone with that link — only share what you're comfortable being
          public. You can disable a share link at any time.</p>
        </Section>

        <Section title="5. No guarantees">
          <p>This service is provided as-is, free of charge, with no uptime or accuracy guarantees.
          Features may change or be removed at any time.</p>
        </Section>

        <Section title="6. Changes">
          <p>These terms may be updated as the app evolves. Continued use after a change means you
          accept the updated terms.</p>
        </Section>

        <Section title="7. Contact">
          <p>Questions? Reach out at <a href="mailto:rohanpgp@gmail.com" style={{ color: 'var(--indigo-500)', fontWeight: 600 }}>rohanpgp@gmail.com</a>.</p>
        </Section>
      </div>
    </div>
  );
}
